name: Deploy to docker hub

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker_homework:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop ${{ secrets.SERVER_USERNAME }}
            docker rm ${{ secrets.SERVER_USERNAME }}
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/docker_homework:latest
            docker run -p ${{ secrets.SERVER_PORT }}:80 -d --name=${{ secrets.SERVER_USERNAME }} ${{ secrets.DOCKER_HUB_USERNAME }}/docker_homework:latest
